spring.application.name=huellitas
server.servlet.context-path=/huellitas
server.port=${PORT:8080}
spring.jpa.open-in-view=false
front.url=${FRONT_URL:http://localhost:5173}
spring.profiles.active=dev

